/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderTravellersResponse } from '../../models/order-travellers-response';

export interface GetOrderTravellers$Params {
  orderId: string;
}

export function getOrderTravellers(http: HttpClient, rootUrl: string, params: GetOrderTravellers$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderTravellersResponse>> {
  const rb = new RequestBuilder(rootUrl, getOrderTravellers.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderTravellersResponse>;
    })
  );
}

getOrderTravellers.PATH = '/api/v1/orders/{orderId}/travellers';
