/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerSessionResponse } from '../../models/customer-session-response';

export interface GetCustomerSession$Params {
}

export function getCustomerSession(http: HttpClient, rootUrl: string, params?: GetCustomerSession$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerSessionResponse>> {
  const rb = new RequestBuilder(rootUrl, getCustomerSession.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerSessionResponse>;
    })
  );
}

getCustomerSession.PATH = '/api/v1/session';
