/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcceptFlightOfferPriceRequest } from '../../models/accept-flight-offer-price-request';
import { ConfirmedFlightOfferResponse } from '../../models/confirmed-flight-offer-response';

export interface AcceptSelectedFlightOfferPrice$Params {
  selectedOfferId: string;
      body: AcceptFlightOfferPriceRequest
}

export function acceptSelectedFlightOfferPrice(http: HttpClient, rootUrl: string, params: AcceptSelectedFlightOfferPrice$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfirmedFlightOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, acceptSelectedFlightOfferPrice.PATH, 'post');
  if (params) {
    rb.path('selectedOfferId', params.selectedOfferId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfirmedFlightOfferResponse>;
    })
  );
}

acceptSelectedFlightOfferPrice.PATH = '/api/v1/flights/selected-offers/{selectedOfferId}/price-acceptances';
