/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfirmedFlightOfferResponse } from '../../models/confirmed-flight-offer-response';

export interface RevalidateSelectedFlightOffer$Params {
  selectedOfferId: string;
}

export function revalidateSelectedFlightOffer(http: HttpClient, rootUrl: string, params: RevalidateSelectedFlightOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfirmedFlightOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, revalidateSelectedFlightOffer.PATH, 'post');
  if (params) {
    rb.path('selectedOfferId', params.selectedOfferId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfirmedFlightOfferResponse>;
    })
  );
}

revalidateSelectedFlightOffer.PATH = '/api/v1/flights/selected-offers/{selectedOfferId}/revalidations';
