/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FlightSearchRequest } from '../../models/flight-search-request';
import { FlightSearchResponse } from '../../models/flight-search-response';

export interface SearchFlights$Params {
      body: FlightSearchRequest
}

export function searchFlights(http: HttpClient, rootUrl: string, params: SearchFlights$Params, context?: HttpContext): Observable<StrictHttpResponse<FlightSearchResponse>> {
  const rb = new RequestBuilder(rootUrl, searchFlights.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FlightSearchResponse>;
    })
  );
}

searchFlights.PATH = '/api/v1/flights/searches';
