/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SelectedFlightOfferResponse } from '../../models/selected-flight-offer-response';
import { SelectFlightOfferRequest } from '../../models/select-flight-offer-request';

export interface SelectFlightOffer$Params {
      body: SelectFlightOfferRequest
}

export function selectFlightOffer(http: HttpClient, rootUrl: string, params: SelectFlightOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectedFlightOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, selectFlightOffer.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SelectedFlightOfferResponse>;
    })
  );
}

selectFlightOffer.PATH = '/api/v1/flights/selected-offers';
