/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefundCaseResponse } from '../../models/refund-case-response';
import { RefundDecisionRequest } from '../../models/refund-decision-request';

export interface DecideRefundCase$Params {
  caseId: string;
      body: RefundDecisionRequest
}

export function decideRefundCase(http: HttpClient, rootUrl: string, params: DecideRefundCase$Params, context?: HttpContext): Observable<StrictHttpResponse<RefundCaseResponse>> {
  const rb = new RequestBuilder(rootUrl, decideRefundCase.PATH, 'post');
  if (params) {
    rb.path('caseId', params.caseId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefundCaseResponse>;
    })
  );
}

decideRefundCase.PATH = '/api/admin/v1/refund-cases/{caseId}/decision';
