/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentEntryResponse } from '../../models/payment-entry-response';

export interface GetPaymentEntry$Params {
}

export function getPaymentEntry(http: HttpClient, rootUrl: string, params?: GetPaymentEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentEntryResponse>> {
  const rb = new RequestBuilder(rootUrl, getPaymentEntry.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentEntryResponse>;
    })
  );
}

getPaymentEntry.PATH = '/api/v1/payments/entry';
