<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\Integrations\Flights\Integrations.Flights.Mock\Integrations.Flights.Mock.csproj" />
    <ProjectReference Include="..\..\..\src\backend\Integrations\Payments\Integrations.Payments.Mock\Integrations.Payments.Mock.csproj" />
  </ItemGroup>

</Project>
