<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\Integrations\Flights\Integrations.Flights.Mock\Integrations.Flights.Mock.csproj" />
    <ProjectReference Include="..\..\..\src\backend\Integrations\Flights\Integrations.Flights.Travelport\Integrations.Flights.Travelport.csproj" />
    <ProjectReference Include="..\..\..\src\backend\Integrations\Flights\Integrations.Flights.Sabre\Integrations.Flights.Sabre.csproj" />
    <ProjectReference Include="..\..\..\src\backend\Integrations\Flights\Integrations.Flights.Duffel\Integrations.Flights.Duffel.csproj" />
    <ProjectReference Include="..\..\..\src\backend\Integrations\Flights\Integrations.Flights.Amadeus\Integrations.Flights.Amadeus.csproj" />
    <ProjectReference Include="..\..\..\src\backend\Integrations\Payments\Integrations.Payments.Mock\Integrations.Payments.Mock.csproj" />
  </ItemGroup>

</Project>
