/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffSessionResponse } from '../../models/staff-session-response';

export interface GetStaffSession$Params {
}

export function getStaffSession(http: HttpClient, rootUrl: string, params?: GetStaffSession$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffSessionResponse>> {
  const rb = new RequestBuilder(rootUrl, getStaffSession.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffSessionResponse>;
    })
  );
}

getStaffSession.PATH = '/api/admin/v1/session';
