/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminCancellationRequest } from '../../models/admin-cancellation-request';
import { CancellationRequestDeclineRequest } from '../../models/cancellation-request-decline-request';

export interface DeclineCancellationRequest$Params {
  requestId: string;
      body: CancellationRequestDeclineRequest
}

export function declineCancellationRequest(http: HttpClient, rootUrl: string, params: DeclineCancellationRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminCancellationRequest>> {
  const rb = new RequestBuilder(rootUrl, declineCancellationRequest.PATH, 'post');
  if (params) {
    rb.path('requestId', params.requestId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminCancellationRequest>;
    })
  );
}

declineCancellationRequest.PATH = '/api/admin/v1/cancellation-requests/{requestId}/decline';
