/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminCancellationRequest } from '../../models/admin-cancellation-request';

export interface ListOpenCancellationRequests$Params {
}

export function listOpenCancellationRequests(http: HttpClient, rootUrl: string, params?: ListOpenCancellationRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AdminCancellationRequest>>> {
  const rb = new RequestBuilder(rootUrl, listOpenCancellationRequests.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AdminCancellationRequest>>;
    })
  );
}

listOpenCancellationRequests.PATH = '/api/admin/v1/cancellation-requests';
