// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBooking.Modules.Flights.Infrastructure;

#nullable disable

namespace TravelBooking.Modules.Flights.Infrastructure.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    [Migration("20260926154139_AddSelectedOfferFare")]
    partial class AddSelectedOfferFare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flights")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBooking.Modules.Flights.Domain.SelectedOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedPriceQuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<string>("Cabin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ConfirmedCurrency")
                        .HasColumnType("char(3)");

                    b.Property<int>("Infants")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OfferExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PriceAcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PriceQuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderOfferToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QuotedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("QuotedCurrency")
                        .HasColumnType("char(3)");

                    b.Property<DateTimeOffset?>("RevalidatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Slices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SlicesJson");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoredFare")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FareJson");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "TravelBooking.Modules.Flights.Domain.SelectedOffer.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SearchId", "OfferId")
                        .IsUnique();

                    b.ToTable("SelectedOffers", "flights", t =>
                        {
                            t.HasCheckConstraint("CK_SelectedOffers_ConfirmedPrice", "([ConfirmedAmount] IS NULL AND [ConfirmedCurrency] IS NULL) OR ([ConfirmedAmount] IS NOT NULL AND [ConfirmedCurrency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SelectedOffers_QuotedPrice", "([QuotedAmount] IS NULL AND [QuotedCurrency] IS NULL) OR ([QuotedAmount] IS NOT NULL AND [QuotedCurrency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SelectedOffers_Status", "[Status] IN ('Selected', 'Confirmed', 'PriceChanged', 'Expired', 'SoldOut')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
