// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBooking.Modules.Flights.Infrastructure;

#nullable disable

namespace TravelBooking.Modules.Flights.Infrastructure.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    partial class FlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flights")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBooking.Modules.Flights.Domain.SelectedOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<string>("Cabin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<int>("Infants")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OfferExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderOfferToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Slices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SlicesJson");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "TravelBooking.Modules.Flights.Domain.SelectedOffer.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SearchId", "OfferId")
                        .IsUnique();

                    b.ToTable("SelectedOffers", "flights");
                });
#pragma warning restore 612, 618
        }
    }
}
