/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcceptHotelPriceRequest } from '../../models/accept-hotel-price-request';
import { ConfirmedHotelOfferResponse } from '../../models/confirmed-hotel-offer-response';

export interface AcceptSelectedHotelOfferPrice$Params {
  selectedOfferId: string;
      body: AcceptHotelPriceRequest
}

export function acceptSelectedHotelOfferPrice(http: HttpClient, rootUrl: string, params: AcceptSelectedHotelOfferPrice$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfirmedHotelOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, acceptSelectedHotelOfferPrice.PATH, 'post');
  if (params) {
    rb.path('selectedOfferId', params.selectedOfferId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfirmedHotelOfferResponse>;
    })
  );
}

acceptSelectedHotelOfferPrice.PATH = '/api/v1/hotels/selected-offers/{selectedOfferId}/price-acceptances';
