/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HotelSearchRequest } from '../../models/hotel-search-request';
import { HotelSearchResponse } from '../../models/hotel-search-response';

export interface SearchHotels$Params {
      body: HotelSearchRequest
}

export function searchHotels(http: HttpClient, rootUrl: string, params: SearchHotels$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelSearchResponse>> {
  const rb = new RequestBuilder(rootUrl, searchHotels.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HotelSearchResponse>;
    })
  );
}

searchHotels.PATH = '/api/v1/hotels/searches';
