/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SelectedHotelOfferResponse } from '../../models/selected-hotel-offer-response';
import { SelectHotelOfferRequest } from '../../models/select-hotel-offer-request';

export interface SelectHotelOffer$Params {
      body: SelectHotelOfferRequest
}

export function selectHotelOffer(http: HttpClient, rootUrl: string, params: SelectHotelOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectedHotelOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, selectHotelOffer.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SelectedHotelOfferResponse>;
    })
  );
}

selectHotelOffer.PATH = '/api/v1/hotels/selected-offers';
