/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AirportResponse {
  cityName: string;
  code: string;
  countryCode: string;
  name: string;
  timeZone: string;
}
