/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BaggageAllowanceResponse {
  cabinBags: number;
  checkedBagMaxWeightKg: (number | null);
  checkedBags: number;
}
