/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CancellationRequestResponse {
  requestId: string;
  requestedAt: string;
  resolvedAt: (string | null);
  status: string;
}
