/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderResponse } from '../models/order-response';
export interface CheckoutResponse {
  customerAction: (string | null);
  order: (null | OrderResponse);
  orderId: string;
  outcome: string;
  payment: string;
}
