/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelAmountResponse } from '../models/hotel-amount-response';
import { HotelCancellationResponse } from '../models/hotel-cancellation-response';
export interface ConfirmedHotelOfferResponse {
  cancellation: HotelCancellationResponse;
  offerExpiresAt: string;
  revalidatedAt: string;
  selectedOfferId: string;
  selectedTotalPrice: HotelAmountResponse;
  totalPrice: HotelAmountResponse;
}
