/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MoneyResponse } from '../models/money-response';
export interface ConfirmedFlightOfferResponse {
  offerExpiresAt: string;
  revalidatedAt: string;
  selectedOfferId: string;
  selectedTotalPrice: MoneyResponse;
  totalPrice: MoneyResponse;
}
