/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AirportResponse } from '../models/airport-response';
import { FlightOfferResponse } from '../models/flight-offer-response';
export interface FlightSearchResponse {
  airports: Array<AirportResponse>;
  offers: Array<FlightOfferResponse>;
  searchId: string;
}
