/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaggageAllowanceResponse } from '../models/baggage-allowance-response';
import { FareAllowance } from '../models/fare-allowance';
import { FlightPriceBreakdownResponse } from '../models/flight-price-breakdown-response';
export interface FlightFareResponse {
  baggage: (null | BaggageAllowanceResponse);
  change: FareAllowance;
  priceBreakdown: (null | FlightPriceBreakdownResponse);
  refund: FareAllowance;
  ticketingDeadline: (string | null);
  validatingCarrier: (string | null);
}
