/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CabinClass } from '../models/cabin-class';
export interface FlightSearchRequest {
  adults?: number;
  cabin?: CabinClass;
  children?: number;
  departureDate: (string | null);
  destination: (string | null);
  infants?: number;
  origin: (string | null);
  returnDate?: (string | null);
}
