/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlightSegmentResponse } from '../models/flight-segment-response';
export interface FlightSliceResponse {
  segments: Array<FlightSegmentResponse>;
}
