/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FlightSegmentResponse {
  arrivalLocal: string;
  departureLocal: string;
  destination: string;
  flightNumber: string;
  marketingCarrier: string;
  origin: string;
}
