/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlightOfferResponse } from '../models/flight-offer-response';
export interface FlightSearchResponse {
  offers: Array<FlightOfferResponse>;
  searchId: string;
}
