/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MoneyResponse } from '../models/money-response';
import { PassengerFareResponse } from '../models/passenger-fare-response';
export interface FlightPriceBreakdownResponse {
  baseFare: MoneyResponse;
  passengers: Array<PassengerFareResponse>;
  taxesAndFees: MoneyResponse;
}
