/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FlightLegSegmentResponse {
  arrivalLocal: string;
  departureLocal: string;
  destination: string;
  destinationTimeZone: (string | null);
  flightNumber: string;
  marketingCarrier: string;
  origin: string;
  originTimeZone: (string | null);
}
