/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlightLegSegmentResponse } from '../models/flight-leg-segment-response';
export interface FlightLegResponse {
  segments: Array<FlightLegSegmentResponse>;
}
