/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlightLegResponse } from '../models/flight-leg-response';
export interface FlightItineraryResponse {
  adults: number;
  cabin: string;
  children: number;
  infants: number;
  legs: Array<FlightLegResponse>;
}
