/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HotelSearchRequest {
  adults?: number;
  checkIn: (string | null);
  checkOut: (string | null);
  childAges?: (Array<number> | null);
  destination: (string | null);
}
