/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HotelStayResponse {
  address: string;
  board: string;
  checkIn: string;
  checkOut: string;
  hotel: string;
  nights: number;
  room: string;
}
