/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoardBasis } from '../models/board-basis';
import { HotelAmountResponse } from '../models/hotel-amount-response';
import { HotelCancellationResponse } from '../models/hotel-cancellation-response';
import { HotelPropertyResponse } from '../models/hotel-property-response';
export interface HotelOfferResponse {
  board: BoardBasis;
  cancellation: HotelCancellationResponse;
  expiresAt: string;
  feesAtProperty: (null | HotelAmountResponse);
  offerId: string;
  property: HotelPropertyResponse;
  room: string;
  totalPrice: HotelAmountResponse;
}
