/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelOfferResponse } from '../models/hotel-offer-response';
export interface HotelSearchResponse {
  nights: number;
  offers: Array<HotelOfferResponse>;
  searchId: string;
}
