/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelAmountResponse } from '../models/hotel-amount-response';
export interface HotelCancellationResponse {
  freeCancellationUntil: (string | null);
  penaltyAfterDeadline: (null | HotelAmountResponse);
  refundable: boolean;
}
