/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoardBasis } from '../models/board-basis';
import { HotelAmountResponse } from '../models/hotel-amount-response';
import { HotelCancellationResponse } from '../models/hotel-cancellation-response';
export interface HotelSelectionProblemResponse {
  board?: (null | BoardBasis);
  cancellation?: (null | HotelCancellationResponse);
  newTotalPrice?: (null | HotelAmountResponse);
  offerExpiresAt?: (string | null);
  previousTotalPrice?: (null | HotelAmountResponse);
  priceQuoteId?: (string | null);
  requiresConfirmation?: (boolean | null);
  room?: (string | null);
  selectedOfferId?: (string | null);
  status: number;
  termsChanged?: (boolean | null);
  title: string;
  traceId?: (string | null);
  type: string;
}
