/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HotelPropertyResponse {
  addressLine: string;
  cityCode: string;
  countryCode: string;
  name: string;
  starRating: (number | null);
  timeZone: string;
}
