/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderResponse } from '../models/order-response';
export interface OrderPage {
  nextCursor: (string | null);
  orders: Array<OrderResponse>;
}
