/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderAmountResponse } from '../models/order-amount-response';
export interface OrderItemResponse {
  agreedPrice: OrderAmountResponse;
  itemId: string;
  offerExpiresAt: string;
  priceChangeAccepted: boolean;
  selectedOfferId: string;
  status: string;
}
