/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItemResponse } from '../models/order-item-response';
export interface OrderResponse {
  createdAt: string;
  items: Array<OrderItemResponse>;
  orderId: string;
  status: string;
}
