/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactResponse } from '../models/contact-response';
import { TravellerResponse } from '../models/traveller-response';
export interface OrderTravellersResponse {
  contact: ContactResponse;
  travellers: Array<TravellerResponse>;
}
