/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderAmountResponse } from '../models/order-amount-response';
import { TravellersNeededResponse } from '../models/travellers-needed-response';
export interface OrderItemResponse {
  agreedPrice: OrderAmountResponse;
  bookingReference: (string | null);
  itemId: string;
  offerExpiresAt: string;
  priceChangeAccepted: boolean;
  product: string;
  selectedOfferId: string;
  status: string;
  ticketing: (string | null);
  travellers: (null | TravellersNeededResponse);
}
