/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CancellationRequestResponse } from '../models/cancellation-request-response';
import { OrderItemResponse } from '../models/order-item-response';
export interface OrderResponse {
  cancellationRequest: (null | CancellationRequestResponse);
  createdAt: string;
  items: Array<OrderItemResponse>;
  orderId: string;
  status: string;
}
