/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CancellationTermsResponse } from '../models/cancellation-terms-response';
import { FlightItineraryResponse } from '../models/flight-itinerary-response';
import { HotelStayResponse } from '../models/hotel-stay-response';
import { OrderAmountResponse } from '../models/order-amount-response';
import { TravellersNeededResponse } from '../models/travellers-needed-response';
export interface OrderItemResponse {
  agreedPrice: OrderAmountResponse;
  bookingReference: (string | null);
  cancellation?: (null | CancellationTermsResponse);
  flight?: (null | FlightItineraryResponse);
  hotel?: (null | HotelStayResponse);
  itemId: string;
  offerExpiresAt: string;
  priceChangeAccepted: boolean;
  product: string;
  selectedOfferId: string;
  status: string;
  ticketing: (string | null);
  travellers: (null | TravellersNeededResponse);
}
