/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MoneyResponse } from '../models/money-response';
import { PassengerType } from '../models/passenger-type';
export interface PassengerFareResponse {
  baseFare: MoneyResponse;
  count: number;
  taxesAndFees: MoneyResponse;
  type: PassengerType;
}
