/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TestPaymentMethodResponse } from '../models/test-payment-method-response';
export interface PaymentEntryResponse {
  mode: string;
  publishableKey: (string | null);
  testMethods: Array<TestPaymentMethodResponse>;
}
