/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SampleRequest {
  from?: (string | null);
  name: (string | null);
  quantity?: number;
  to?: (string | null);
}
