/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactRequest } from '../models/contact-request';
import { TravellerRequest } from '../models/traveller-request';
export interface SaveTravellersRequest {
  contact: (null | ContactRequest);
  travellers: Array<TravellerRequest>;
}
