/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoardBasis } from '../models/board-basis';
import { HotelAmountResponse } from '../models/hotel-amount-response';
import { HotelCancellationResponse } from '../models/hotel-cancellation-response';
import { HotelPropertyResponse } from '../models/hotel-property-response';
export interface SelectedHotelOfferResponse {
  board: BoardBasis;
  cancellation: HotelCancellationResponse;
  checkIn: string;
  checkOut: string;
  nights: number;
  offerExpiresAt: string;
  offerId: string;
  property: HotelPropertyResponse;
  room: string;
  searchId: string;
  selectedOfferId: string;
  totalPrice: HotelAmountResponse;
}
