/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlightSliceResponse } from '../models/flight-slice-response';
import { MoneyResponse } from '../models/money-response';
export interface SelectedFlightOfferResponse {
  offerExpiresAt: string;
  offerId: string;
  searchId: string;
  selectedOfferId: string;
  slices: Array<FlightSliceResponse>;
  totalPrice: MoneyResponse;
}
