/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MoneyResponse } from '../models/money-response';
export interface SelectedOfferProblemResponse {
  newTotalPrice?: (null | MoneyResponse);
  offerExpiresAt?: (string | null);
  previousTotalPrice?: (null | MoneyResponse);
  priceQuoteId?: (string | null);
  requiresConfirmation?: (boolean | null);
  selectedOfferId?: (string | null);
  status: number;
  title: string;
  traceId?: (string | null);
  type: string;
}
