/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravelDocumentKind } from '../models/travel-document-kind';
export interface TravelDocumentRequest {
  expiryDate: (string | null);
  issuingCountry: (string | null);
  nationality: (string | null);
  number: (string | null);
  type: (null | TravelDocumentKind);
}
