/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravellersNeededResponse {
  adults: number;
  ageOn?: (string | null);
  children: number;
  documentsRequired: boolean;
  infants: number;
}
