/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TravellerGenderType } from '../models/traveller-gender-type';
import { TravellerType } from '../models/traveller-type';
export interface TravellerRequest {
  dateOfBirth: (string | null);
  gender: (null | TravellerGenderType);
  givenNames: (string | null);
  surname: (string | null);
  type: (null | TravellerType);
}
