/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TravellerResponse {
  dateOfBirth: (string | null);
  documentProvided: boolean;
  gender: (string | null);
  givenNames: (string | null);
  position: number;
  surname: (string | null);
  type: string;
}
