/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleChangeDecisionRequest } from '../../models/role-change-decision-request';
import { RoleChangeResponse } from '../../models/role-change-response';

export interface DecideRoleChange$Params {
  requestId: string;
      body: RoleChangeDecisionRequest
}

export function decideRoleChange(http: HttpClient, rootUrl: string, params: DecideRoleChange$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleChangeResponse>> {
  const rb = new RequestBuilder(rootUrl, decideRoleChange.PATH, 'post');
  if (params) {
    rb.path('requestId', params.requestId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleChangeResponse>;
    })
  );
}

decideRoleChange.PATH = '/api/admin/v1/access/role-changes/{requestId}/decision';
