/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleGrantResponse } from '../../models/role-grant-response';

export interface ListRoleGrants$Params {
}

export function listRoleGrants(http: HttpClient, rootUrl: string, params?: ListRoleGrants$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleGrantResponse>>> {
  const rb = new RequestBuilder(rootUrl, listRoleGrants.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleGrantResponse>>;
    })
  );
}

listRoleGrants.PATH = '/api/admin/v1/access/role-grants';
