/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleChangePage } from '../../models/role-change-page';

export interface ListRoleChanges$Params {
  status?: string;
  limit?: number;
  cursor?: string;
}

export function listRoleChanges(http: HttpClient, rootUrl: string, params?: ListRoleChanges$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleChangePage>> {
  const rb = new RequestBuilder(rootUrl, listRoleChanges.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('limit', params.limit, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleChangePage>;
    })
  );
}

listRoleChanges.PATH = '/api/admin/v1/access/role-changes';
