/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleChangeRequestRequest } from '../../models/role-change-request-request';
import { RoleChangeResponse } from '../../models/role-change-response';

export interface RequestRoleChange$Params {
      body: RoleChangeRequestRequest
}

export function requestRoleChange(http: HttpClient, rootUrl: string, params: RequestRoleChange$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleChangeResponse>> {
  const rb = new RequestBuilder(rootUrl, requestRoleChange.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleChangeResponse>;
    })
  );
}

requestRoleChange.PATH = '/api/admin/v1/access/role-changes';
