/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleRequest } from '../../models/sample-request';
import { SampleResponse } from '../../models/sample-response';

export interface ValidateSample$Params {
      body: SampleRequest
}

export function validateSample(http: HttpClient, rootUrl: string, params: ValidateSample$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleResponse>> {
  const rb = new RequestBuilder(rootUrl, validateSample.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SampleResponse>;
    })
  );
}

validateSample.PATH = '/api/v1/sample/validation';
