/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookingReviewCheckRequest } from '../../models/booking-review-check-request';
import { BookingReviewCheckResponse } from '../../models/booking-review-check-response';

export interface CheckBookingReview$Params {
  orderId: string;
  itemId: string;
      body: BookingReviewCheckRequest
}

export function checkBookingReview(http: HttpClient, rootUrl: string, params: CheckBookingReview$Params, context?: HttpContext): Observable<StrictHttpResponse<BookingReviewCheckResponse>> {
  const rb = new RequestBuilder(rootUrl, checkBookingReview.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.path('itemId', params.itemId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookingReviewCheckResponse>;
    })
  );
}

checkBookingReview.PATH = '/api/admin/v1/orders/{orderId}/items/{itemId}/review-checks';
