/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrderDetail } from '../../models/admin-order-detail';

export interface GetOrderForOperations$Params {
  orderId: string;
}

export function getOrderForOperations(http: HttpClient, rootUrl: string, params: GetOrderForOperations$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrderDetail>> {
  const rb = new RequestBuilder(rootUrl, getOrderForOperations.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrderDetail>;
    })
  );
}

getOrderForOperations.PATH = '/api/admin/v1/orders/{orderId}';
