/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrderPage } from '../../models/admin-order-page';

export interface ListOrdersForOperations$Params {
  itemStatus?: string;
  limit?: number;
  cursor?: string;
}

export function listOrdersForOperations(http: HttpClient, rootUrl: string, params?: ListOrdersForOperations$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrderPage>> {
  const rb = new RequestBuilder(rootUrl, listOrdersForOperations.PATH, 'get');
  if (params) {
    rb.query('itemStatus', params.itemStatus, {});
    rb.query('limit', params.limit, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrderPage>;
    })
  );
}

listOrdersForOperations.PATH = '/api/admin/v1/orders';
