/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefundCaseResponse } from '../../models/refund-case-response';

export interface ListOrderRefundCases$Params {
  orderId: string;
}

export function listOrderRefundCases(http: HttpClient, rootUrl: string, params: ListOrderRefundCases$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RefundCaseResponse>>> {
  const rb = new RequestBuilder(rootUrl, listOrderRefundCases.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RefundCaseResponse>>;
    })
  );
}

listOrderRefundCases.PATH = '/api/admin/v1/orders/{orderId}/refund-cases';
