/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefundCaseRequest } from '../../models/refund-case-request';
import { RefundCaseResponse } from '../../models/refund-case-response';

export interface OpenRefundCase$Params {
  orderId: string;
  'Idempotency-Key'?: string;
      body: RefundCaseRequest
}

export function openRefundCase(http: HttpClient, rootUrl: string, params: OpenRefundCase$Params, context?: HttpContext): Observable<StrictHttpResponse<RefundCaseResponse>> {
  const rb = new RequestBuilder(rootUrl, openRefundCase.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefundCaseResponse>;
    })
  );
}

openRefundCase.PATH = '/api/admin/v1/orders/{orderId}/refund-cases';
