/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminAmount } from '../models/admin-amount';
export interface AdminRefund {
  amount: AdminAmount;
  providerRefundId: (string | null);
  reason: (string | null);
  refundId: string;
  requestedAt: string;
  settledAt: (string | null);
  status: string;
}
