/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminOrderSummary } from '../models/admin-order-summary';
import { AdminTimelineEntry } from '../models/admin-timeline-entry';
export interface AdminOrderDetail {
  order: AdminOrderSummary;
  timeline: Array<AdminTimelineEntry>;
}
