/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminOrderSummary } from '../models/admin-order-summary';
export interface AdminOrderPage {
  nextCursor: (string | null);
  orders: Array<AdminOrderSummary>;
}
