/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CancellationTermsResponse } from '../models/cancellation-terms-response';
export interface AdminHotelStay {
  address: string;
  agreedCancellation: (null | CancellationTermsResponse);
  board: string;
  booked: boolean;
  checkIn: string;
  checkOut: string;
  cityCode: string;
  countryCode: string;
  hotel: string;
  itemId: string;
  nights: number;
  room: string;
  timeZone: string;
}
