/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminCancellationRequest {
  customerId: string;
  orderId: string;
  requestId: string;
  requestedAt: string;
  resolutionNote: (string | null);
  resolvedAt: (string | null);
  resolvedBy: (string | null);
  status: string;
}
