/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminCancellationRequest } from '../models/admin-cancellation-request';
import { AdminHotelStay } from '../models/admin-hotel-stay';
import { AdminOrderSummary } from '../models/admin-order-summary';
import { AdminTimelineEntry } from '../models/admin-timeline-entry';
export interface AdminOrderDetail {
  cancellationRequest: (null | AdminCancellationRequest);
  order: AdminOrderSummary;
  stays: Array<AdminHotelStay>;
  timeline: Array<AdminTimelineEntry>;
}
