/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminOrderItem } from '../models/admin-order-item';
export interface AdminOrderSummary {
  createdAt: string;
  customerId: string;
  items: Array<AdminOrderItem>;
  orderId: string;
  paymentId: (string | null);
  status: string;
}
