/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderAmountResponse } from '../models/order-amount-response';
export interface AdminOrderItem {
  agreedPrice: OrderAmountResponse;
  bookingReference: (string | null);
  bookingStartedAt: (string | null);
  itemId: string;
  providerId: (string | null);
  selectedOfferId: string;
  status: string;
  ticketing: (string | null);
}
