/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminTimelineEntry {
  actor: string;
  at: string;
  correlationId: (string | null);
  fromStatus: (string | null);
  itemId: (string | null);
  providerReference: (string | null);
  reason: string;
  toStatus: string;
}
