/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookingReviewCheckResponse {
  itemId: string;
  itemStatus: string;
  orderId: string;
  resolved: boolean;
}
