/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookingReviewOutcome } from '../models/booking-review-outcome';
export interface BookingReviewOutcomeRequest {
  outcome: (null | BookingReviewOutcome);
  priceNotAboveAgreed?: boolean;
  reason: (string | null);
  sameTravellersAndFlights?: boolean;
  supplierReference?: (string | null);
}
