/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderAmountResponse } from '../models/order-amount-response';
export interface CancellationTermsResponse {
  freeCancellationUntil: (string | null);
  penaltyAfterDeadline: (null | OrderAmountResponse);
  refundable: boolean;
}
