/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LegalHoldReleaseResponse } from '../models/legal-hold-release-response';
export interface LegalHoldStatusResponse {
  anonymised: boolean;
  held: boolean;
  orderId: string;
  pendingRelease: (null | LegalHoldReleaseResponse);
  purgeNotBefore: (string | null);
}
