/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LegalHoldReleaseResponse {
  decidedAt: (string | null);
  decidedBy: (string | null);
  orderId: string;
  reason: string;
  requestId: string;
  requestedAt: string;
  requestedBy: string;
  status: string;
}
