/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderAmountResponse } from '../models/order-amount-response';
export interface RefundCaseResponse {
  amount: OrderAmountResponse;
  caseId: string;
  decidedAt: (string | null);
  decidedBy: (string | null);
  fee: string;
  itemIds: Array<string>;
  kind: string;
  orderId: string;
  reason: string;
  requestedAt: string;
  requestedBy: string;
  settledAt: (string | null);
  status: string;
  supplierReference: (string | null);
  supplierRefund: (string | null);
}
