/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RefundCaseKind } from '../models/refund-case-kind';
export interface RefundCaseRequest {
  amount?: (string | null);
  itemIds?: (Array<string> | null);
  kind: (null | RefundCaseKind);
  reason: (string | null);
  supplierReference?: (string | null);
  supplierRefund?: (string | null);
}
