/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleChangeResponse } from '../models/role-change-response';
export interface RoleChangePage {
  nextCursor: (string | null);
  requests: Array<RoleChangeResponse>;
}
