/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleGrantResponse {
  grantedAt: (string | null);
  grantedByRequestId: (string | null);
  objectId: string;
  role: string;
  source: string;
}
