/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleChangeAction } from '../models/role-change-action';
export interface RoleChangeRequestRequest {
  action: (null | RoleChangeAction);
  objectId: (string | null);
  reason: (string | null);
  role: (string | null);
}
