/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleChangeResponse {
  action: string;
  decidedAt: (string | null);
  decidedBy: (string | null);
  objectId: string;
  requestId: string;
  requestedAt: string;
  requestedBy: string;
  role: string;
  status: string;
}
