/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { SearchFlights$Params as SearchFlights$Params } from './fn/flights/search-flights';
export { searchFlights as searchFlights } from './fn/flights/search-flights';
