/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ValidateSample$Params as ValidateSample$Params } from './fn/sample/validate-sample';
export { validateSample as validateSample } from './fn/sample/validate-sample';
