/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { provideApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { Api } from './api';

export type { CabinClass } from './models/cabin-class';
export type { FlightOfferResponse } from './models/flight-offer-response';
export type { FlightSearchRequest } from './models/flight-search-request';
export type { FlightSearchResponse } from './models/flight-search-response';
export type { FlightSegmentResponse } from './models/flight-segment-response';
export type { FlightSliceResponse } from './models/flight-slice-response';
export type { HttpValidationProblemDetails } from './models/http-validation-problem-details';
export type { MoneyResponse } from './models/money-response';
export type { ProblemDetails } from './models/problem-details';

export type { SearchFlights$Params as SearchFlights$Params } from './fn/flights/search-flights';
export { searchFlights as searchFlights } from './fn/flights/search-flights';
