/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { provideApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { Api } from './api';

export type { HttpValidationProblemDetails } from './models/http-validation-problem-details';
export type { SampleRequest } from './models/sample-request';
export type { SampleResponse } from './models/sample-response';

export type { ValidateSample$Params as ValidateSample$Params } from './fn/sample/validate-sample';
export { validateSample as validateSample } from './fn/sample/validate-sample';
