/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CabinClass } from './models/cabin-class';
export type { FlightOfferResponse } from './models/flight-offer-response';
export type { FlightSearchRequest } from './models/flight-search-request';
export type { FlightSearchResponse } from './models/flight-search-response';
export type { FlightSegmentResponse } from './models/flight-segment-response';
export type { FlightSliceResponse } from './models/flight-slice-response';
export type { HttpValidationProblemDetails } from './models/http-validation-problem-details';
export type { MoneyResponse } from './models/money-response';
export type { ProblemDetails } from './models/problem-details';
export type { SelectedFlightOfferResponse } from './models/selected-flight-offer-response';
export type { SelectFlightOfferRequest } from './models/select-flight-offer-request';
