/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AcceptFlightOfferPriceRequest } from './models/accept-flight-offer-price-request';
export type { AirportResponse } from './models/airport-response';
export type { BaggageAllowanceResponse } from './models/baggage-allowance-response';
export type { CabinClass } from './models/cabin-class';
export type { ConfirmedFlightOfferResponse } from './models/confirmed-flight-offer-response';
export type { FareAllowance } from './models/fare-allowance';
export type { FlightFareResponse } from './models/flight-fare-response';
export type { FlightOfferResponse } from './models/flight-offer-response';
export type { FlightPriceBreakdownResponse } from './models/flight-price-breakdown-response';
export type { FlightSearchRequest } from './models/flight-search-request';
export type { FlightSearchResponse } from './models/flight-search-response';
export type { FlightSegmentResponse } from './models/flight-segment-response';
export type { FlightSliceResponse } from './models/flight-slice-response';
export type { HttpValidationProblemDetails } from './models/http-validation-problem-details';
export type { MoneyResponse } from './models/money-response';
export type { PassengerFareResponse } from './models/passenger-fare-response';
export type { PassengerType } from './models/passenger-type';
export type { ProblemDetails } from './models/problem-details';
export type { SelectedFlightOfferResponse } from './models/selected-flight-offer-response';
export type { SelectedOfferProblemResponse } from './models/selected-offer-problem-response';
export type { SelectFlightOfferRequest } from './models/select-flight-offer-request';
