/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { HttpValidationProblemDetails } from './models/http-validation-problem-details';
export type { SampleRequest } from './models/sample-request';
export type { SampleResponse } from './models/sample-response';
