/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CheckoutRequest } from '../../models/checkout-request';
import { CheckoutResponse } from '../../models/checkout-response';

export interface CheckoutOrder$Params {
  orderId: string;
  'Idempotency-Key'?: string;
      body: CheckoutRequest
}

export function checkoutOrder(http: HttpClient, rootUrl: string, params: CheckoutOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<CheckoutResponse>> {
  const rb = new RequestBuilder(rootUrl, checkoutOrder.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CheckoutResponse>;
    })
  );
}

checkoutOrder.PATH = '/api/v1/orders/{orderId}/checkout';
