/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateFlightOrderRequest } from '../../models/create-flight-order-request';
import { OrderResponse } from '../../models/order-response';

export interface CreateFlightOrder$Params {
  'Idempotency-Key'?: string;
      body: CreateFlightOrderRequest
}

export function createFlightOrder(http: HttpClient, rootUrl: string, params: CreateFlightOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderResponse>> {
  const rb = new RequestBuilder(rootUrl, createFlightOrder.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderResponse>;
    })
  );
}

createFlightOrder.PATH = '/api/v1/orders';
