/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderPage } from '../../models/order-page';

export interface ListMyOrders$Params {
  limit?: number;
  cursor?: string;
}

export function listMyOrders(http: HttpClient, rootUrl: string, params?: ListMyOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderPage>> {
  const rb = new RequestBuilder(rootUrl, listMyOrders.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderPage>;
    })
  );
}

listMyOrders.PATH = '/api/v1/orders';
