/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CancellationRequestResponse } from '../../models/cancellation-request-response';

export interface RequestCancellation$Params {
  orderId: string;
  'Idempotency-Key'?: string;
}

export function requestCancellation(http: HttpClient, rootUrl: string, params: RequestCancellation$Params, context?: HttpContext): Observable<StrictHttpResponse<CancellationRequestResponse>> {
  const rb = new RequestBuilder(rootUrl, requestCancellation.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CancellationRequestResponse>;
    })
  );
}

requestCancellation.PATH = '/api/v1/orders/{orderId}/cancellation-requests';
