/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CancellationRequestResponse } from '../../models/cancellation-request-response';

export interface WithdrawCancellationRequest$Params {
  orderId: string;
  requestId: string;
}

export function withdrawCancellationRequest(http: HttpClient, rootUrl: string, params: WithdrawCancellationRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<CancellationRequestResponse>> {
  const rb = new RequestBuilder(rootUrl, withdrawCancellationRequest.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.path('requestId', params.requestId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CancellationRequestResponse>;
    })
  );
}

withdrawCancellationRequest.PATH = '/api/v1/orders/{orderId}/cancellation-requests/{requestId}/withdrawal';
