/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminPaymentAttempt } from '../../models/admin-payment-attempt';

export interface GetPaymentAttemptForOperations$Params {
  attemptId: string;
}

export function getPaymentAttemptForOperations(http: HttpClient, rootUrl: string, params: GetPaymentAttemptForOperations$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminPaymentAttempt>> {
  const rb = new RequestBuilder(rootUrl, getPaymentAttemptForOperations.PATH, 'get');
  if (params) {
    rb.path('attemptId', params.attemptId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminPaymentAttempt>;
    })
  );
}

getPaymentAttemptForOperations.PATH = '/api/admin/v1/payments/{attemptId}';
