/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentReviewResolutionRequest } from '../../models/payment-review-resolution-request';
import { RefundReviewResolutionResponse } from '../../models/refund-review-resolution-response';

export interface ResolveRefundReview$Params {
  refundId: string;
      body: PaymentReviewResolutionRequest
}

export function resolveRefundReview(http: HttpClient, rootUrl: string, params: ResolveRefundReview$Params, context?: HttpContext): Observable<StrictHttpResponse<RefundReviewResolutionResponse>> {
  const rb = new RequestBuilder(rootUrl, resolveRefundReview.PATH, 'post');
  if (params) {
    rb.path('refundId', params.refundId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RefundReviewResolutionResponse>;
    })
  );
}

resolveRefundReview.PATH = '/api/admin/v1/payments/refunds/{refundId}/review-resolutions';
