/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentReviewResolutionRequest } from '../../models/payment-review-resolution-request';
import { PaymentReviewResolutionResponse } from '../../models/payment-review-resolution-response';

export interface ResolvePaymentReview$Params {
  attemptId: string;
      body: PaymentReviewResolutionRequest
}

export function resolvePaymentReview(http: HttpClient, rootUrl: string, params: ResolvePaymentReview$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentReviewResolutionResponse>> {
  const rb = new RequestBuilder(rootUrl, resolvePaymentReview.PATH, 'post');
  if (params) {
    rb.path('attemptId', params.attemptId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentReviewResolutionResponse>;
    })
  );
}

resolvePaymentReview.PATH = '/api/admin/v1/payments/{attemptId}/review-resolutions';
