/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LegalHoldReleaseDecisionRequest } from '../../models/legal-hold-release-decision-request';
import { LegalHoldReleaseResponse } from '../../models/legal-hold-release-response';

export interface DecideLegalHoldRelease$Params {
  requestId: string;
      body: LegalHoldReleaseDecisionRequest
}

export function decideLegalHoldRelease(http: HttpClient, rootUrl: string, params: DecideLegalHoldRelease$Params, context?: HttpContext): Observable<StrictHttpResponse<LegalHoldReleaseResponse>> {
  const rb = new RequestBuilder(rootUrl, decideLegalHoldRelease.PATH, 'post');
  if (params) {
    rb.path('requestId', params.requestId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LegalHoldReleaseResponse>;
    })
  );
}

decideLegalHoldRelease.PATH = '/api/admin/v1/legal-hold/release-requests/{requestId}/decision';
