/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LegalHoldStatusResponse } from '../../models/legal-hold-status-response';

export interface GetLegalHold$Params {
  orderId: string;
}

export function getLegalHold(http: HttpClient, rootUrl: string, params: GetLegalHold$Params, context?: HttpContext): Observable<StrictHttpResponse<LegalHoldStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getLegalHold.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LegalHoldStatusResponse>;
    })
  );
}

getLegalHold.PATH = '/api/admin/v1/orders/{orderId}/legal-hold';
