/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LegalHoldReleaseResponse } from '../../models/legal-hold-release-response';

export interface ListLegalHoldReleaseRequests$Params {
}

export function listLegalHoldReleaseRequests(http: HttpClient, rootUrl: string, params?: ListLegalHoldReleaseRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LegalHoldReleaseResponse>>> {
  const rb = new RequestBuilder(rootUrl, listLegalHoldReleaseRequests.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LegalHoldReleaseResponse>>;
    })
  );
}

listLegalHoldReleaseRequests.PATH = '/api/admin/v1/legal-hold/release-requests';
