/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LegalHoldReleaseRequestRequest } from '../../models/legal-hold-release-request-request';
import { LegalHoldReleaseResponse } from '../../models/legal-hold-release-response';

export interface RequestLegalHoldRelease$Params {
  orderId: string;
      body: LegalHoldReleaseRequestRequest
}

export function requestLegalHoldRelease(http: HttpClient, rootUrl: string, params: RequestLegalHoldRelease$Params, context?: HttpContext): Observable<StrictHttpResponse<LegalHoldReleaseResponse>> {
  const rb = new RequestBuilder(rootUrl, requestLegalHoldRelease.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LegalHoldReleaseResponse>;
    })
  );
}

requestLegalHoldRelease.PATH = '/api/admin/v1/orders/{orderId}/legal-hold/release-requests';
