/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LegalHoldStateRequest } from '../../models/legal-hold-state-request';
import { LegalHoldStateResponse } from '../../models/legal-hold-state-response';

export interface SetLegalHold$Params {
  orderId: string;
      body: LegalHoldStateRequest
}

export function setLegalHold(http: HttpClient, rootUrl: string, params: SetLegalHold$Params, context?: HttpContext): Observable<StrictHttpResponse<LegalHoldStateResponse>> {
  const rb = new RequestBuilder(rootUrl, setLegalHold.PATH, 'put');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LegalHoldStateResponse>;
    })
  );
}

setLegalHold.PATH = '/api/admin/v1/orders/{orderId}/legal-hold';
