// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBooking.Modules.Hotels.Infrastructure;

#nullable disable

namespace TravelBooking.Modules.Hotels.Infrastructure.Migrations
{
    [DbContext(typeof(HotelsDbContext))]
    [Migration("20261007132947_AddBookedSelectionStatus")]
    partial class AddBookedSelectionStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hotels")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBooking.Modules.Hotels.Domain.HotelSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedPriceQuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<string>("ChildAges")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal?>("ConfirmedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ConfirmedCurrency")
                        .HasColumnType("char(3)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal?>("FeesAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("FeesCurrency")
                        .HasColumnType("char(3)");

                    b.Property<DateTimeOffset?>("FreeCancellationUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OfferExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PenaltyAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("PenaltyCurrency")
                        .HasColumnType("char(3)");

                    b.Property<DateTimeOffset?>("PriceAcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PriceQuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderOfferToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QuotedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("QuotedCurrency")
                        .HasColumnType("char(3)");

                    b.Property<bool>("Refundable")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("RevalidatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RoomDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("StarRating")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TermsChanged")
                        .HasColumnType("bit");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "TravelBooking.Modules.Hotels.Domain.HotelSelection.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("char(3)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SearchId", "OfferId", "CustomerId")
                        .IsUnique();

                    b.ToTable("Selections", "hotels", t =>
                        {
                            t.HasCheckConstraint("CK_Selections_ConfirmedPrice", "([ConfirmedAmount] IS NULL AND [ConfirmedCurrency] IS NULL) OR ([ConfirmedAmount] IS NOT NULL AND [ConfirmedCurrency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Selections_FeesPrice", "([FeesAmount] IS NULL AND [FeesCurrency] IS NULL) OR ([FeesAmount] IS NOT NULL AND [FeesCurrency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Selections_PenaltyPrice", "([PenaltyAmount] IS NULL AND [PenaltyCurrency] IS NULL) OR ([PenaltyAmount] IS NOT NULL AND [PenaltyCurrency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Selections_QuotedPrice", "([QuotedAmount] IS NULL AND [QuotedCurrency] IS NULL) OR ([QuotedAmount] IS NOT NULL AND [QuotedCurrency] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Selections_Status", "[Status] IN ('Selected', 'Confirmed', 'PriceChanged', 'Expired', 'SoldOut', 'Booking', 'Booked')");

                            t.HasCheckConstraint("CK_Selections_Stay", "[CheckOut] > [CheckIn]");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
